#!/bin/sh

echo -n "파일 /디렉토리 이름 입력 [enter]"
read fname

if [ -L "$fname" ]; then
	echo "$fname 은 심볼릭 링크입니다."
elif [ ! -e "$fname" ]; then
	echo "$fname 은 존재하지 않습니다."
elif [ -d "$fname" ]; then
	echo "$fname 은디렉토리입니다."
elif [ -c "$fname" ]; then
	echo "$fname 은 문자 장치입니다."
elif [ -b "$fname" ]; then
	echo "$fname 은 블록 장치입니다."
elif [ -p "$fname" ]; then
	echo "$fn`ame 은 파이프입니다."
elif [ -s "$fname" ]; then
	echo "$fname 은 소켓입니다."
elif [ -f "$fname" ]; then
	echo "$fname 은 보통 파일입니다."
else 
	echo "$fname 은 알 수 없는 파일 유형입니다."
fi 
